server:
  servlet:
    context-path: /ai

spring:
  ai:
    deepseek:
      api-key: ${API_KEY}  #在IDE run configuration加上环境变量
      base-url: https://api.deepseek.com/v1
      chat:
        options:
#          model: deepseek-reasoner
          model: deepseek-chat